name: Build & Release Experimental Turnip Drivers

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Release Experimental Turnip Drivers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            patchelf \
            unzip \
            flex \
            bison \
            git \
            perl \
            python3-pip \
            glslang-tools \
            curl \
            zip

          pip3 install \
            --break-system-packages \
            meson \
            mako

      - name: Build Experimental Turnip Drivers
        run: |
          chmod +x build_turnip.sh
          export BUILD_VERSION="${{ github.run_number }}"
          ./build_turnip.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Experimental-Turnip-Drivers
          path: turnip_workdir/*.zip
          if-no-files-found: error
          retention-days: 30

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Experimental Turnip Drivers v${{ github.run_number }}
          files: turnip_workdir/*.zip
          generate_release_notes: true
